export const MINIMUM_ARTICLE_TITLE_LENGTH = 5;
export const MAXIMUM_ARTICLE_TITLE_LENGTH = 50;

export const MINIMUM_ARTICLE_SUB_TITLE_LENGTH = 5;
export const MAXIMUM_ARTICLE_SUB_TITLE_LENGTH = 50;

export const MINIMUM_ARTICLE_CONTENT_LENGTH = 10;
export const MAXIMUM_ARTICLE_CONTENT_LENGTH = 100_000;
